Improve the README.md to make it clear and simple to follow
ocp-power-automation/ocp4-upi-powervs pull request #106
Opened 2020-09-30 21:31 UTC by rpsene

Signed-off-by: Rafael Peria de Sene <rpsene@br.ibm.com>

2020-09-30 21:31 UTC, ltccci commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/106#" title="Author self-approved">rpsene</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **prajyot-parab**
You can assign the PR to them by writing `/assign @prajyot-parab` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["prajyot-parab"]} -->

2020-10-01 05:59 UTC, bpradipt commented on README.md
> -:heavy_exclamation_mark: **Ensure that you're working from the desired release-specific version of this `README` as you deploy by first selecting the appropriate branch from the drop-down above. At t
Please do not delete this text for now. This is specifically added for first time users to try stable release.

2020-10-01 06:00 UTC, bpradipt commented
@clnperez can you please review the changes..

2020-10-03 09:48 UTC, yussufsh commented
/approve
Look simpler and better for me.

2020-10-03 09:48 UTC, ltccci commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/106#" title="Author self-approved">rpsene</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/106#issuecomment-703077884" title="Approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/OWNERS)~~ [yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-10-03 14:55 UTC, clnperez commented
Was out for a few days. Will review ASAP @bpradipt.

2020-10-06 10:30 UTC, bpradipt commented
@rpsene will need a rebase.. 
The doc looks good to me.. Will wait for comments from @clnperez

2020-10-06 16:42 UTC, clnperez requested changes
Mostly small grammar comments. The only real suggestion is to put the PowerVS info into the PowerVS pre-req doc instead of here.

2020-10-06 16:42 UTC, clnperez commented on README.md
> +This repository contains Terraform templates, configurations and automation which leverages the [helpernode ansible playbook](https://github.com/RedHatOfficial/ocp4-helpernode) to assist on deploying
one nit: to assist *in* deploying

2020-10-06 16:42 UTC, clnperez commented on README.md
> +:heavy_exclamation_mark: ensure that you're working from the desired release-specific version of this `README` as you deploy by first selecting the appropriate branch from the drop-down above. At the
nit: capitalize the first letters in sentences "For any bugs..." "Check ou  the latest..." "Ensure that you're..."

2020-10-06 16:42 UTC, clnperez commented on README.md
> +You need to handle an initial preparation in your PowerVS instance to successfuly execute this automation. Follow this [guide](docs/ocp_prereqs_powervs.md) to get it done. To get started with PowerVS
Suggested verbiage: "You first need to create and configure a PowerVS Intance in IBM Cloud before running this automation. You may follow [this guide](docs/ocp_prereqs_powervs.md) for instructions."

The other information, I think, should be moved to the PowerVS pre-reqs doc.

2020-10-06 16:42 UTC, clnperez commented on README.md
> +You can run this automation from any system (laptop, virtual machine, etc.) with internet access. It was tested on the following operating systems:
"It has been tested on the following..."

2020-10-15 12:40 UTC, bpradipt commented
@rpsene can you please rebase and send the updated PR.

2020-10-15 16:29 UTC, rpsene commented
@bpradipt done!

2020-10-15 23:10 UTC, clnperez commented
@rpsene can you move this "about powervs" powervs detail to the prereq doc? 

`
To get started with PowerVS, [click here](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-getting-started). You can also learn more about PowerVS by watching some YouTube videos by clicking [here](https://www.youtube.com/watch?v=RywSfXT_LLs) and [here](https://www.youtube.com/playlist?list=PLVrJaTKVPbKM_9HU8fm4QsklgzLGUwFpv).
`

It's good info. I just think having it all listed there is distracting.

2020-10-15 23:21 UTC, rpsene commented
> @rpsene can you move this "about powervs" powervs detail to the prereq doc?
> 
> `To get started with PowerVS, [click here](https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-getting-started). You can also learn more about PowerVS by watching some YouTube videos by clicking [here](https://www.youtube.com/watch?v=RywSfXT_LLs) and [here](https://www.youtube.com/playlist?list=PLVrJaTKVPbKM_9HU8fm4QsklgzLGUwFpv).`
> 
> It's good info. I just think having it all listed there is distracting.

Why distracting if we have users that have difficult getting started with the basic steps on PowerVS? I would like to keep it in the front page so it is easy to find.

2020-10-16 19:47 UTC, clnperez commented
To me, it seems like too much is going on (too many links and places to diverge into) in that one little snippet. My brain would read this easier if we point users to the more in-depth PowerVS guide (as is done in the first sentence), and there include the additional info about PowerVS.

2021-02-17 11:12 UTC, bpradipt commented
Closing this as this is stale PR.

2021-02-17 11:12 UTC, closed without merging