Add actiovationkey support for RHEL subscription
ocp-power-automation/ocp4-upi-powervs pull request #210
Opened 2021-01-21 21:02 UTC by cs-zhang

2021-01-21 21:02 UTC, ltccci commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/210#" title="Author self-approved">cs-zhang</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **bpradipt** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @bpradipt` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["bpradipt"]} -->

2021-01-22 06:03 UTC, yussufsh commented
@cs-zhang Please sign the commit with your name and email address.
https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/CONTRIBUTING.md#pull-request-process

2021-01-22 16:33 UTC, cs-zhang commented
I have added the signed-off-by, but I could not find it here. Where is it?

2021-01-25 15:18 UTC, cs-zhang commented
/assign @bpradipt

2021-01-27 06:42 UTC, yussufsh requested changes

2021-01-27 06:42 UTC, yussufsh commented on docs/var.tfvars-doc.md
> +These set of variables specify the RHEL subscription details, RHEL subscription supports two motheds: one is using username and password, the other is using activation key.
motheds-> methods

2021-01-27 06:43 UTC, bpradipt commented on docs/var.tfvars-doc.md
> +These set of variables specify the RHEL subscription details, RHEL subscription supports two motheds: one is using username and password, the other is using activation key.
motheds -> methods

2021-01-27 15:52 UTC, cs-zhang commented on docs/var.tfvars-doc.md
> +These set of variables specify the RHEL subscription details, RHEL subscription supports two motheds: one is using username and password, the other is using activation key.
Fixed the typo.

2021-01-28 03:07 UTC, yussufsh approved these changes
/lgtm

2021-01-28 03:07 UTC, ltccci commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/210#" title="Author self-approved">cs-zhang</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/210#pullrequestreview-577952245" title="LGTM">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/OWNERS)~~ [yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-01-28 13:06 UTC, bpradipt approved these changes
/lgtm

2021-01-28 13:06 UTC, ltccci commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/210#pullrequestreview-578312157" title="LGTM">bpradipt</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/210#" title="Author self-approved">cs-zhang</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/210#pullrequestreview-577952245" title="LGTM">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/OWNERS)~~ [bpradipt,yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-01-28 13:07 UTC, merged