Use the image storage pool for volumes and instances
ocp-power-automation/ocp4-upi-powervs pull request #337
Opened 2021-11-29 05:50 UTC by yussufsh

Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>

2021-11-29 05:50 UTC, yussufsh commented
/cc @aishwaryabk @rpsene @bpradipt @Prajyot-Parab

2021-11-29 05:51 UTC, yussufsh commented
Fixes #330 #307

2021-11-29 06:01 UTC, Prajyot-Parab submitted a review, later dismissed
/lgtm

2021-11-29 06:02 UTC, aishwaryabk submitted a review, later dismissed
/lgtm

2021-11-29 13:32 UTC, mkumatag requested changes

2021-11-29 13:32 UTC, mkumatag commented on modules/1_prepare/prepare.tf
> +  }
why are we assigning twice here?

2021-11-29 13:58 UTC, mkumatag approved these changes
Please make sure we add proper documentation in the release notes because we are changing the variable names, and also update the description in the PR about the networking changes done.

/lgtm

2021-11-29 14:57 UTC, Prajyot-Parab approved these changes
/approve

2021-11-29 14:58 UTC, merged

2021-11-29 15:09 UTC, yussufsh commented
/backport release-4.8

2021-11-29 15:09 UTC, yussufsh commented
/backport release-4.7

2021-11-29 15:09 UTC, yussufsh commented
/backport release-4.6

2021-11-29 15:13 UTC, yussufsh commented
/cherry-pick release-4.9

2021-11-29 15:15 UTC, yussufsh commented
/cherry-pick release-4.8

2021-11-29 15:15 UTC, yussufsh commented
/cherry-pick release-4.7

2021-11-29 15:15 UTC, yussufsh commented
/cherry-pick release-4.6

2021-11-30 00:46 UTC, yussufsh commented
/cherry-pick release-4.8

2021-11-30 00:46 UTC, yussufsh commented
/cherry-pick release-4.7

2021-11-30 00:47 UTC, yussufsh commented
/cherry-pick release-4.6