Support adding DNS entries for CIS service based cluster domain
ocp-power-automation/ocp4-upi-powervs pull request #498
Opened 2023-11-18 14:23 UTC by Prajyot-Parab

- Support adding DNS entries for CIS service based cluster domain

2023-11-18 14:25 UTC, Prajyot-Parab commented
/cc @yussufsh 
This is critical for the MAC P2 CI

2023-11-20 05:11 UTC, yussufsh requested changes
@Prajyot-Parab Please rebase to take CIS changes.

2023-11-20 05:11 UTC, yussufsh commented on ocp.tf
> +  bastion_ip        = module.prepare.bastion_ip
use bastion_vip in case count > 1

2023-11-20 05:11 UTC, yussufsh commented on ocp.tf
> +  bastion_public_ip = module.prepare.bastion_public_ip
Use bastion_external_vip in case count > 1

2023-11-20 05:11 UTC, yussufsh commented on modules/6_post_install/cis.tf
> +  content   = var.bastion_public_ip[0]
variable can be string.

2023-11-20 05:11 UTC, yussufsh commented on modules/6_post_install/cis.tf
> +  content   = var.bastion_ip[0]
variable can be string.

2023-11-20 05:11 UTC, yussufsh commented on modules/6_post_install/cis.tf
> +  content   = var.bastion_public_ip[0]
variable can be string.

2023-11-20 05:11 UTC, yussufsh commented on modules/6_post_install/cis.tf
> +################################################################
Can you please rename the dir to `8_custom`

2023-11-20 12:48 UTC, yussufsh requested changes

2023-11-20 12:48 UTC, yussufsh commented on docs/quickstart.md
> +>**Note**: If you are using IBM Cloud Internet Services (CIS) for `cluster_domain`, ensure you set `ibm_cloud_cis_crn`.
Rephrase:
If you just need to add the DNS entries in the CIS domain zone without using IBM Cloud Services eg: VPC Load Balancer, then set `ibm_cloud_cis_crn` with the CIS domain CRN and keep `use_ibm_cloud_services = false`.

2023-11-20 12:48 UTC, yussufsh commented on modules/8_custom/cis.tf
> +}
We do not need internal DNS entry. This will be used from bastion for the cluster operations.

2023-11-21 05:19 UTC, yussufsh approved these changes
/lgtm

2023-11-21 05:19 UTC, merged